---
- hosts: web
  become: yes
  tasks:
    - name: Installs apache web server
      dnf:
        name: httpd
        state: present
        update_cache: true

    - name: Push default virtual host configuration
      copy:
        src: files/awesome-app
        dest: /tmp/awesome-app1.conf
        mode: 0640

    - name: Activates our virtualhost
      file:
        src: /tmp/awesome-app.conf
        dest: /tmp/awesome-app.conf
        state: link
      notify:
        - restart apache

    - name: Disable the default ssl virtualhost
      file:
        dest: /tmp/default-ssl.conf
        state: absent
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

